using System;
using TowerSoft.Repository.Maps;

namespace TowerSoft.Repository.Builders {
    /// <summary>
    /// Fluent map builder used in the EntityMap class
    /// </summary>
    public partial class PropertyMapBuilder : IEquatable<PropertyMapBuilder> {
        private string PropertyName { get; }
        private bool IsAutonumber { get; set; }
        private bool IsID { get; set; }
        private bool IsFilemanDateMap { get; set; }
        private bool IsHorologDateMap { get; set; }

        /// <summary>
        /// PropertyMapBuilder constructor
        /// </summary>
        /// <param name="propertyName"></param>
        public PropertyMapBuilder(string propertyName) {
            PropertyName = propertyName;
        }

        /// <summary>
        /// Maps the property to a column name
        /// </summary>
        /// <param name="columnName">Column name in the database</param>
        /// <returns></returns>
        public IMap To(string columnName) {
            return GetReturnMap(columnName);
        }

        /// <summary>
        /// Maps the property to a column with the same name
        /// </summary>
        /// <returns></returns>
        public IMap ToSameName() {
            return GetReturnMap(null);
        }

        /// <summary>
        /// Marks the property as not mapped. Use this to overide a map generated by the auto mapping option.
        /// </summary>
        /// <returns></returns>
        public IMap NotMapped() {
            return new Map(PropertyName, null);
        }

        /// <summary>
        /// Marks the map as an autonumber map. Use this for primary keys that auto increment
        /// </summary>
        /// <returns></returns>
        public PropertyMapBuilder AsAutonumber() {
            IsAutonumber = true;
            return this;
        }

        /// <summary>
        /// Marks the map as an ID map. Use this for primary keys that do not auto increment
        /// </summary>
        /// <returns></returns>
        public PropertyMapBuilder AsPrimaryKey() {
            IsID = true;
            return this;
        }

        /// <summary>
        /// Marks the map as an ID map. Use this for primary keys that do not auto increment
        /// </summary>
        /// <returns></returns>
        [Obsolete("Use AsPrimaryKey instead")]
        public PropertyMapBuilder AsID() {
            IsID = true;
            return this;
        }

        /// <summary>
        /// Marks the map as a Fileman date map. Only use this on Intersystems Caché databases.
        /// </summary>
        /// <returns></returns>
        public PropertyMapBuilder AsFilemanDateMap() {
            IsFilemanDateMap = true;
            return this;
        }

        /// <summary>
        /// Marks the map as a $HOROLOG date map. Only use this on Intersystems Caché databases
        /// </summary>
        /// <returns></returns>
        public PropertyMapBuilder AsHorologDateMap() {
            IsHorologDateMap = true;
            return this;
        }

        private IMap GetReturnMap(string columnName = null) {
            if (IsAutonumber)
                return new AutonumberMap(PropertyName, columnName ?? PropertyName);
            else if (IsID)
                return new IDMap(PropertyName, columnName ?? PropertyName);
            else if (IsFilemanDateMap)
                return new CacheFilemanDateMap(PropertyName, columnName ?? PropertyName);
            else if (IsHorologDateMap)
                return new CacheHorologDateMap(PropertyName, columnName ?? PropertyName);
            return new Map(PropertyName, columnName ?? PropertyName);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode() {
            return PropertyName.ToLower().GetHashCode();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="other"></param>
        /// <returns></returns>
        public bool Equals(PropertyMapBuilder other) {
            return other != null && PropertyName.Equals(other.PropertyName, StringComparison.InvariantCultureIgnoreCase);
        }
    }
}
